server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 5
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 20
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

minio:
  endpoint: http://localhost:9000
  access-key: minio
  secret-key: minioadmin
  bucket: test